dist: bionic

# Python 3.6 or greater is required by svdtools.
language: python
python:
  - "3.6"
  # - "3.7"
  # - "3.8"

# Installing all requirements, then build and install svdtools.
install:
  - pip install -U -r dev-requirements.txt
  # TODO: add requirements.txt (?)
  - pip install -U PyYAML
  - flit install --symlink

before_script:
  # Pull down all files stored using LFS before executing our tests.
  - git lfs pull
  # Checkout the stm32-rs repository for testing purposes.
  # TODO: once #331 is merged, clone from upstream repo
  # TODO: replace below with git checkout $COMMIT (?)
  - git clone -b use-svdtools --single-branch https://github.com/nickray/stm32-rs.git tests/stm32-rs/

script:
  # Ensure that both `black` and `isort` have been run prior to actual testing.
  # TODO: do we want to hard fail on these?
  - black --check svdtools/
  - isort --check-only --recursive svdtools/
  # Patch all stm32-rs SVDs using the current build of svdtools.
  - cd tests/stm32-rs/ && make patch && cd ../../
  # Diff the known-good patched SVDs and their counterparts generated by the
  # current build of svdtools.
  - bash tests/diff_patched_svds.sh
